Vagrant.configure("2") do |config|
  config.vm.define "WEB" do |web|
	
	#VM BOX Ubuntu 
	web.vm.box = "ubuntu/xenial64"
  
	#VM Hostname
	web.vm.hostname = "Ubuntu-WEB"

	#Sync Folder
	web.vm.synced_folder "./Shared_WEB", "/var/www/html"
  
	#VM Network
	web.vm.network "private_network", ip: "192.168.1.10"
	web.vm.network "forwarded_port", guest: 80, host: 8080

	#Script
	web.vm.provision :shell, path: "config_web.sh"
	
	#VM Disksize
	web.disksize.size = '10GB'
  
	#VM Provider and Specs
	web.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.name = "Ubuntu-WEB"
		vb.cpus = "2"
		vb.gui = true
	end
  end
  
  config.vm.define "FTP" do |ftp|
	
	#VM BOX Ubuntu 
	ftp.vm.box = "ubuntu/xenial64"
  
	#VM Hostname
	ftp.vm.hostname = "Ubuntu-ftp"
  
	#VM Network
	ftp.vm.network "private_network", ip: "192.168.1.20"

	#Script
	ftp.vm.provision :shell, path: "config_ftp.sh"
	ftp.vm.network "forwarded_port", guest: 20, host: 420
	ftp.vm.network "forwarded_port", guest: 21, host: 421

	#VM Disksize
	ftp.disksize.size = '10GB'
  
	#VM Provider and Specs
	ftp.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.name = "Ubuntu-ftp"
		vb.cpus = "2"
		vb.gui = true
	end
  end  
 end