Vagrant.configure("2") do |config|

  config.vm.define "WEB" do |subconfig|
	
	#VM BOX Ubuntu 
	subconfig.vm.box = "ubuntu/xenial64"
  
	#VM Hostname
	subconfig.vm.hostname = "Ubuntu-WEB"
	
	#Sync Folder
	subconfig.vm.synced_folder ".", "/var/www/html"
  
	#VM Network
	subconfig.vm.network "private_network", ip: "192.168.1.20"
	subconfig.vm.network "forwarded_port", guest: 80, host: 8080
	
	#VM Disksize
	subconfig.disksize.size = '10GB'
	
	#Software
	subconfig.vm.provision "shell", inline: <<-SHELL
		apt-get update
		apt-get install apache2 -y
		sudo sed -i 's/XKBLAYOUT="us"/XKBLAYOUT="ch"/g' /etc/default/locale
	SHELL
		
	#VM Provider and Specs
	subconfig.vm.provider "virtualbox" do |vb|
		vb.memory = "4096"
		vb.name = "Ubuntu-WEB"
		vb.cpus = "4"
		vb.gui = true
	end	
  end  
 end