Vagrant.configure("2") do |config|

  #VM BOX Ubuntu 
  config.vm.box = "ubuntu/xenial64"

  #VM Network Settings
  config.vm.network "private_network", ip:"192.168.1.50"
  config.vm.network "forwarded_port", guest:8080, host:8080, auto_correct: true
  config.vm.network "forwarded_port", guest:1020, host:1020, auto_correct: true

  #VM Hostname  
  config.vm.hostname = "docker"

  #Script
	config.vm.provision :shell, path: "config_docker.sh"
      
  #Sync Folder
  config.vm.synced_folder "./Shared_Docker", "/vagrant"

  #VM Provider and Specs
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.name = "Docker" 
		 vb.cpus = "2"
		 vb.gui = true
  end

  # Docker Provisioner
  config.vm.provision "docker" do |d|
   d.pull_images "ubuntu:16.04"
  end
end